In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",   
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good."
]



In [3]:
voc_size=10000


In [4]:
## one hot representation 

one_hot_rep=[one_hot(words,voc_size) for words in sent]


In [5]:
one_hot_rep

[[1615, 1168, 8583, 1095],
 [1615, 1168, 8583, 3338],
 [1615, 6950, 8583, 1790],
 [1585, 4699, 7062, 219, 3579],
 [1585, 4699, 7062, 219, 338],
 [1932, 1615, 6475, 8583, 5274],
 [7721, 9607, 9525, 219]]

In [12]:
## Word Embedding Representation 

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [13]:
import numpy as np 


In [14]:
sent_length=8

embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1615 1168 8583 1095]
 [   0    0    0    0 1615 1168 8583 3338]
 [   0    0    0    0 1615 6950 8583 1790]
 [   0    0    0 1585 4699 7062  219 3579]
 [   0    0    0 1585 4699 7062  219  338]
 [   0    0    0 1932 1615 6475 8583 5274]
 [   0    0    0    0 7721 9607 9525  219]]


In [15]:
## Feature Representation 
dim=10


In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build((None, sent_length))  # Build the model with input shape
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[[ 0.03786783,  0.01348401, -0.02812928, -0.03094162,
          0.00038296,  0.00345157, -0.02885701,  0.02187297,
          0.00241963, -0.04839844],
        [ 0.03786783,  0.01348401, -0.02812928, -0.03094162,
          0.00038296,  0.00345157, -0.02885701,  0.02187297,
          0.00241963, -0.04839844],
        [ 0.03786783,  0.01348401, -0.02812928, -0.03094162,
          0.00038296,  0.00345157, -0.02885701,  0.02187297,
          0.00241963, -0.04839844],
        [ 0.03786783,  0.01348401, -0.02812928, -0.03094162,
          0.00038296,  0.00345157, -0.02885701,  0.02187297,
          0.00241963, -0.04839844],
        [-0.04660115,  0.0262883 ,  0.03627365,  0.03742737,
         -0.03837859,  0.02418417, -0.02347058, -0.01900533,
          0.03241077,  0.01527412],
        [-0.02472827, -0.03045706,  0.00732009, -0.02869778,
          0.04147864,  0.02631922,  0.03651217,  0.0053501 ,
         -0.03937643, -0.02118944],
        [-0.0373166 , -0.01202454, -0.02850633, -0.0

In [26]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[ 0.03786783,  0.01348401, -0.02812928, -0.03094162,  0.00038296,
         0.00345157, -0.02885701,  0.02187297,  0.00241963, -0.04839844],
       [ 0.03786783,  0.01348401, -0.02812928, -0.03094162,  0.00038296,
         0.00345157, -0.02885701,  0.02187297,  0.00241963, -0.04839844],
       [ 0.03786783,  0.01348401, -0.02812928, -0.03094162,  0.00038296,
         0.00345157, -0.02885701,  0.02187297,  0.00241963, -0.04839844],
       [ 0.03786783,  0.01348401, -0.02812928, -0.03094162,  0.00038296,
         0.00345157, -0.02885701,  0.02187297,  0.00241963, -0.04839844],
       [-0.04660115,  0.0262883 ,  0.03627365,  0.03742737, -0.03837859,
         0.02418417, -0.02347058, -0.01900533,  0.03241077,  0.01527412],
       [-0.02472827, -0.03045706,  0.00732009, -0.02869778,  0.04147864,
         0.02631922,  0.03651217,  0.0053501 , -0.03937643, -0.02118944],
       [-0.0373166 , -0.01202454, -0.02850633, -0.01408168,  0.02791304,
        -0.04802761, -0.00815196, -0.03581661