Numpy is a fundamental library for scientific computing in Python.It provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures. In this lession,we will cover the basics of Numpy,focusing on arrays and vectorized operators.


In [5]:
import numpy as np

## Create a 1D array with numpy
data=np.array([1,2,3,4]) ## inside this we can give list ,tuple or dict
datatuple=np.array((1,4,'array'))
datadict=np.array({1:'anup',2:'sudip'})
print(data)
print(datatuple)
print(datadict)
print(type(data))
print(type(datatuple))


[1 2 3 4]
['1' '4' 'array']
{1: 'anup', 2: 'sudip'}
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
arr=np.array([1,2,3,4,5])
print(arr.shape)
arr.reshape(1,5) ## 1 row and 5 columns 

(5,)


array([[1, 2, 3, 4, 5]])

In [14]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
## 2-D array
arr1=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr1)
print(arr1.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [23]:
np.arange(0,10,2).reshape(5,1)  ##first creates array in range with step then reshape based on row and column


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [25]:
np.ones((3,4)) ## initialize the array with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
zeroarr=np.zeros((1,5))
zeroarr.shape

(1, 5)

In [31]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
arr2=np.array([[1,2,3],[4,5,6]])

## printing attributes of arr
print(arr2.ndim) ## dimension 
print(arr2.dtype) ## data type
print(arr2.size) ## size of array len 
print(arr2.itemsize) ## total array item size 
print(arr2.shape) ## shape of arrray 

2
int64
6
8
(2, 3)


In [36]:
## numpy vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,4,6,8])

print("Addition :",arr1+arr2)
print("Addition :",arr1-arr2)
print("Multiplication: ",arr1*arr2)
print("Division: ",arr1/arr2)


Addition : [ 3  5  7 10 13]
Addition : [-1 -1 -1 -2 -3]
Multiplication:  [ 2  6 12 24 40]
Division:  [0.5        0.66666667 0.75       0.66666667 0.625     ]


In [37]:
## Universal function

arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## EXponential 
print(np.exp(arr))

## sin
print(np.sin(arr))

## log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [46]:
## Array Slicing and Indexing

arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n ",arr1)

get_rows=arr1.shape[0]
get_col=arr1.shape[1]

get1st_row=arr1[0][:]
print(get1st_row)



Array :
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [47]:
arr1[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr1[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [65]:
arr1[0:2,:2]

array([[1, 2],
       [5, 6]])

In [67]:
arr1[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [69]:
## modify array elements
arr1[0,0]=100
print(arr1)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr1[1:]=100
print(arr1)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [71]:
## Statistical concepts --Normalization

## change the data to have a mean of 0 and standard deviation of 1


data=np.array([1,2,3,4,5])

## calculate mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

normalized_data=(data-mean)/std_dev

print("Normalized Data: ",normalized_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [78]:
## Logical Operation

data=np.array([1,2,3,4,5,6,7,8,9])

data[(data>5) & (data<8)] 

array([6, 7])